language: java
# Cache the Maven repository per branch, so that we avoid downloading artifacts each time...
cache:
  directories:
    - $HOME/.m2
install: true
script: mvn -s settings.xml clean install -Pdist -DpreferIpv4
jdk:
  - oraclejdk8
